import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <div className="bg-white fixed left-8 top-40 z-10 w-[9%] h-[800px] hidden sm:inline">광고 사이드 배너</div>
        <div className="bg-white fixed right-8 top-40 z-10 w-[9%] h-[800px] hidden sm:inline">광고 사이드 배너</div>
      </body>
    </html>
  );
}
